### PR TITLE
bugfix/IIA-994-dnd-notworking-post-merge

### PR DESCRIPTION
**Pull request by dholubek**
both double click and drag and drop pattern summoning are working

image

also check that existing concept drag and drop is working:
image

next gen dnd still working:
image

right click populate on next gen search still working:
image

### CODE REVIEW

**Comment by dukke** [comment]
Looks good to me!

**Review by dukke — APPROVED** [review]

**Review by swaroopsalvi — COMMENTED** [review]
Looks good.
Have question, 
How did changing Entity to EntityFacade fix this any issue?

**Review by carldea — APPROVED** [review]
Looks good to me!

**Comment by dholubek** [comment]
> Looks good. Have question, How did changing Entity to EntityFacade fix this any issue?

it was a class cast exception.

**Pull request merged**
